[features]
seeds = false
[programs.localnet]
ft = "3Fzp351iQFQHLS2ePYBsE9uiRr9xee5tyyxzUHjEpak2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kelvin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
